config/routes.rb
Rails.application.routes.draw do

  scope constraints: { subdomain: 'manager'} do

    resources :users, only: [:index, :create, :new]

    devise_for :users, :skip => [:registrations, :sessions]

    as :user do
      get "/login" => "devise/sessions#new", :as => :new_user_session
      post "/login" => "devise/sessions#create", :as => :user_session
      delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    devise_for :admins, controllers: { registrations: "admins/registrations" }

    devise_scope :admin do
      authenticated :admin do
        root 'events#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    resources :clients, only: [:new, :create, :index]

    resources :events do
      get :past, on: :collection
      resources :participants, only: [:create, :new]
      resources :event_receptionists, only: [:create, :new]
      resources :checklists, only: [:create, :new, :destroy]
    end
    resources :admins, :only => [:show]

  end



  #api definition
  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1 do
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :creator, class_name: 'Admin'
  belongs_to :event_type

  has_many :participants, dependent: :destroy
  has_many :companies, through: :participants

  has_many :checklists
  has_many :clients, through: :checklists
  has_many :event_receptionists
  has_many :receptionists, class_name: 'User', through: :event_receptionists

  validates :name, :slug, :start_at, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  delegate :name, to: :event_type, prefix: true
  scope :past, -> { where("start_at < ?", Time.zone.now) }
  scope :coming, -> { where("start_at >= ?", Time.zone.now) }

  def generate_slug
    self.slug = "#{name.parameterize}-#{Time.current.to_i}"
  end

  def full_address
    "#{address} - #{location}"
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base

  validates :name, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = current_company.events.coming.includes(:clients, :creator, :event_type, :companies, :receptionists).paginate(:page => params[:page], :per_page => 12).order(:start_at)
  end

  def show
    @event = Event.includes(:companies, :clients).find(params[:id])
    @checklists = @event.checklists.includes(:client).order('clients.fullname')
  end

  def new
    @event = Event.new(start_at: Time.zone.now)
  end

  def past
    @events = current_company.events.past.includes(:clients, :creator, :event_type, :companies).paginate(:page => params[:page], :per_page => 12).order(:start_at)
    render 'index'
  end

  def create
    @event = current_admin.events.new(params_event)
    @event.company_id = current_admin.company_id
    if @event.save
      @event.company_ids = current_admin.company_id
      flash[:success] = "Evento creado!"
      redirect_to @event
    else
      render 'new'
    end
  end


  private

  def params_event
    params.require(:event).permit(:name, :start_at, :duration, :place, :latitude, :longitude, :address, :location, :description, :event_type_id)
  end
end

app/helpers/event_helper.rb
module EventHelper
  def event_status_class(start_at)
    if start_at < Time.zone.now
      'inactive'
    else
      'active'
    end
  end
end

app/views/events/_event.html.haml
.col-sm-4
  .item-event{id: dom_id(event), class: "#{event_status_class(event.start_at)}"}
    = link_to event, class: 'event-show-link' do
      .event-header
        %h3.name= event.name.titleize
        %p.event-type= event.event_type_name.titleize
        %p.icon-header
          %i.fa.fa-map-marker.fa-lg
          = event.full_address
        %p.icon-header
          %i.fa.fa-calendar-o.fa-lg
          = l(event.start_at, format: :short)

    .event-content
      %ul.companies

        - if event.companies.size > 6
          %li.aditional-company= "+#{event.companies.size - 6}"

        - event.companies.to_a.take(6).each do |company|
          %li
            %span{title: "#{company.name}", class: 'tipsy-add'}= image_tag(Company::LOGO_URLS.sample, class: 'avatar-icon')

  .options
    .row
      .col-sm-4.col
        %span.icon-option
          %i.fa.fa-user
          = event.clients.size
        %span.icon-text
          Invitados

      .col-sm-4.middle.col
        %span.icon-option
          %i.fa.fa-building
          = event.companies.size
        %span.icon-text
          Organizadores

      .col-sm-4.col
        %span.icon-option
          %i.fa.fa-street-view
          = event.receptionists.size
        %span.icon-text
          Recepcionistas

app/views/events/_form.html.haml
= simple_form_for @event,  html: { class: 'form-horizontal' } do |f|
  / = render 'shared/error_messages', object: f.object
  = f.input :name, autofocus: true
  = f.association :event_type, prompt: '- Tipo de evento -'
  = f.input :start_at, as: :datetime_picker
  = f.input :duration
  .location_event
    .wrapper-map
      = f.input :place, input_html: {placeholder: 'p.e Los sopranos'}
      = f.input :location, input_html: {data: {geo: 'formatted_address'}, class: 'location'}
      = f.input :longitude, input_html: {data: {geo: 'lng'}}, as: :hidden
      = f.input :latitude, input_html: {data: {geo: 'lat'}}, as: :hidden
      = f.input :address, input_html: {placeholder: 'p.e Avenida Nro 345'}
    #my_map

  = f.input :description, input_html: { :rows => 6}
  = f.submit 'Crear', class: 'btn btn-primary'
  / %button.btn Cancelar

app/views/events/index.html.haml
.container
  %h2= t '.title'
  .sort-container
    %section{class: 'segmented-control'}
      = link_to 'En curso', events_path, class: 'segmented-control__segment'
      = link_to 'Pasados', past_events_path, class: 'segmented-control__segment'
  - if @events.any?
    - @events.in_groups_of(3, false) do |events|
      .row.events= render events

    .paginate
      = will_paginate @events

app/views/events/new.html.haml
.container
  .wrapper-title
    %h2.title Nuevo evento
  .row
    .col-sm-8.col-md-offset-2
      = render 'form'

app/views/events/show.html.haml
.event-show
  .row.event-header
    .col-sm-12
      .row
        .col-sm-4.col-md-offset-4
          %h3.title
            = @event.name.titleize
          %span= @event.event_type.name
          .info-desc
            %ul.companies-list
              %li
                = link_to new_event_participant_path(@event), {title: 'Agregar compañias', :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'circle-add-link tipsy-add'} do
                  .circle-add
                    +

              - @event.companies.each do |company|
                %li
                  %span{title: "#{company.name}", class: 'tipsy-add'}= image_tag(Company::LOGO_URLS.sample, class: 'avatar-icon')

  .container
    .row.event-info
      .col-sm-6
        .info-desc
          %p.info-desc
            %i.fa.fa-map-marker.fa-lg
            = @event.full_address

          %p
            %i.fa.fa-calendar-o.fa-lg
            = l @event.start_at, format: :short

          %p
            %i.fa.fa-clock-o.fa-lg
            = "#{@event.duration} hrs"

          %p
            %i.fa.fa-user.fa-lg
            = @event.creator.fullname

      .col-sm-6
        .info-desc
          %p.event-desc
            = @event.description

        .info-desc.event-desc
          %ul.receptionist-list
            %li
              = link_to new_event_event_receptionist_path(@event), {title: 'Agregar recepcionista', :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'circle-add-link tipsy-add'} do
                .circle-add
                  +
            - @event.receptionists.each do |receptionist|
              %li
                %span{title: "#{receptionist.fullname}", class: 'tipsy-add'}= image_tag(Company::LOGO_URLS.sample, class: 'avatar-icon')


    .row
      .col-sm-6
        %fieldset
          %legend
            Mis Invitados
            = link_to '+ Agrega un invitado', new_event_checklist_path(@event),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn-add-client'}

          %ul.checklist-list
            - unless @checklists.blank?
              = render @checklists
            - else
              Aún no tienes ningun invitado