config/routes.rb
Rails.application.routes.draw do

  scope constraints: { subdomain: 'manager'} do

    resources :users, only: [:index, :create, :new]

    devise_for :users, :skip => [:registrations, :sessions]

    as :user do
      get "/login" => "devise/sessions#new", :as => :new_user_session
      post "/login" => "devise/sessions#create", :as => :user_session
      delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    devise_for :admins, controllers: { registrations: "admins/registrations" }

    devise_scope :admin do
      authenticated :admin do
        root 'events#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    resources :clients, only: [:new, :create, :index]

    resources :events do
      get :past, on: :collection
      resources :participants, only: [:create, :new]
      resources :event_receptionists, only: [:create, :new]
      resources :checklists, only: [:create, :new, :destroy]
    end
    resources :admins, :only => [:show]

  end



  #api definition
  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1 do
    end
  end

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  belongs_to :event
  belongs_to :client

  validates :client_id, :event_id, presence: true
  validates :client_id, uniqueness: { scope: :event_id, message: "Ya elegiste el cliente" }

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @event = Event.find(params[:event_id])
    @checklist = @event.checklists.build(params_checklist)
    @checklist.company_id = current_admin.company_id
    if @checklist.save
      flash[:success] = "Invitado agregado!"
      redirect_to @event
    else
      flash[:error] = "Ocurrio un error!"
      redirect_to @event
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    @checklist = Checklist.find(params[:id])
    @checklist.destroy
    redirect_to event
  end

  private
  def params_checklist
    params.require(:checklist).permit(:client_id)
  end
end

app/views/checklists/_checklist.html.haml
%li
  %span.option-name= checklist.client.fullname
  %span.option-delete= link_to 'Eliminar', [@event, checklist], method: :delete,  data: { confirm: 'Are you sure?' }
  %span.email= checklist.client.email

app/views/checklists/_form.html.haml
= simple_form_for [@event, Checklist.new] do |f|
  = f.association :client, collection: current_admin.clients, label_method: :fullname
  = f.submit 'Agregar', class: 'btn btn-primary'

app/views/checklists/_new.html.haml
.add-clients-to-checklist
  = simple_form_for [@event, Checklist.new] do |f|
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      .icon-add-client
        %i.fa.fa-users
      %h3.title-add Agrega Invitados a tu Lista
      = f.association :client, collection: current_admin.clients, label_method: :fullname, label: false, prompt: "- Elija un cliente - ", autofocus: true
    .modal-body
      %p.not-found
        No encontraste al cliente? crea por
        = link_to 'aqui', new_client_path
    .modal-footer
      = f.submit 'AGREGAR', class: 'btn btn-primary'