config/routes.rb
Rails.application.routes.draw do

  scope constraints: { subdomain: 'manager'} do

    resources :users, only: [:index, :create, :new]

    devise_for :users, :skip => [:registrations, :sessions]

    as :user do
      get "/login" => "devise/sessions#new", :as => :new_user_session
      post "/login" => "devise/sessions#create", :as => :user_session
      delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    devise_for :admins, controllers: { registrations: "admins/registrations" }

    devise_scope :admin do
      authenticated :admin do
        root 'events#index', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    resources :clients, only: [:new, :create, :index]

    resources :events do
      get :past, on: :collection
      resources :participants, only: [:create, :new]
      resources :event_receptionists, only: [:create, :new]
      resources :checklists, only: [:create, :new, :destroy]
    end
    resources :admins, :only => [:show]

  end



  #api definition
  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1 do
    end
  end

end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Eventos check list", authenticated_root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to 'Nuevo Evento', new_event_path, class: 'btn-new-event'

        %li.dropdown
          %a{ href: "#", class: "dropdown-toggle", data: { "toggle" => "dropdown" } }
            Account
            %span.caret
          %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
            %li= link_to "Mis eventos", events_path
            %li= link_to "Mis Recepcionistas", '#'
            %li= link_to "Mis Clientes", clients_path
            / %li.divider
            / %li Campañas
            / %li Reportes
            %li.divider
            %li= link_to "Perfil", edit_admin_registration_path
            %li= link_to "Mi Empresa", '#'
            %li= link_to "Log out", destroy_admin_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title EventsBackend
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    = csrf_meta_tags
  %body
    - if admin_signed_in?
      = render 'layouts/header'
      .container-fluid
        - flash.each do |message_type, message|
          %div{class: "#{flash_class(message_type)}"}= message
        = yield
    - else
      .container
        = yield
    #modal-window.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?libraries=places'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/login.html.haml
!!!
%html
  %head
    %title EventsBackend - Login
    = stylesheet_link_tag  'login', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
    = csrf_meta_tags
  %body
    .overlay
    .container
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true